/*
 * This file is generated by Entity Class Compiler, (c) CroTeam 1997-98
 */

#line 20 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"

#include <Engine/StdH.h>
#include <Engine/Entities/InternalClasses.h>
#include <Engine/Base/Stream.h>
#include <Engine/Base/CRC.h>

#include <Engine/Classes/PlayerEntity.h>
#include <Engine/Classes/PlayerEntity_tables.h>
void CPlayerEntity::SetDefaultProperties(void) {
  en_tmPing = 0.0f;
  CMovableModelEntity::SetDefaultProperties();
}
  CTString CPlayerEntity::GetPlayerName(void) 
#line 42 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 43 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
return en_pcCharacter  . GetNameForPrinting  ();
#line 44 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  const CTString & CPlayerEntity::GetName(void)const 
#line 46 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 47 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
return en_pcCharacter  . GetName  ();
#line 48 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  INDEX CPlayerEntity::GetMyPlayerIndex(void) 
#line 51 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 52 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CEntity  * penMe  = this ;
#line 53 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
if(IsPredictor  ()){
#line 54 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
penMe  = GetPredicted  ();
#line 55 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
#line 57 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
INDEX iPlayer ;
#line 58 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
for(iPlayer  = 0;iPlayer  < GetMaxPlayers  ();iPlayer  ++){
#line 60 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
if(GetPlayerEntity  (iPlayer ) == penMe ){
#line 61 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
return iPlayer ;
#line 62 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
#line 63 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
#line 65 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
return 15;
#line 66 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::DoMoving(void) 
#line 70 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 71 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: DoMoving  ();
#line 72 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::Copy(CEntity & enOther,ULONG ulFlags) 
#line 76 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 77 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: Copy  (enOther  , ulFlags );
#line 79 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CPlayerEntity  * ppenOther  = (CPlayerEntity  *) (& enOther );
#line 80 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
en_pcCharacter  = ppenOther  -> en_pcCharacter ;
#line 81 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
en_plViewpoint  = ppenOther  -> en_plViewpoint ;
#line 82 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
en_plLastViewpoint  = ppenOther  -> en_plLastViewpoint ;
#line 83 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::Read_t(CTStream * istr) 
#line 95 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 96 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: Read_t  (istr );
#line 97 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
(* istr ) >> en_pcCharacter  >> en_plViewpoint ;
#line 98 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
en_plLastViewpoint  = en_plViewpoint ;
#line 99 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::Write_t(CTStream * ostr) 
#line 102 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 103 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: Write_t  (ostr );
#line 104 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
(* ostr ) << en_pcCharacter  << en_plViewpoint ;
#line 105 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::ApplyAction(const CPlayerAction & pa,FLOAT tmLatency) {}
  void CPlayerEntity::Disconnect(void) {}
  void CPlayerEntity::CharacterChanged(const CPlayerCharacter & pcNew) {en_pcCharacter  = pcNew ;}
  void CPlayerEntity::GetGameAgentPlayerInfo(INDEX iPlayer,CTString & strOut) {}
  void CPlayerEntity::GetMSLegacyPlayerInf(INDEX iPlayer,CTString & strOut) {}
  void CPlayerEntity::ChecksumForSync(ULONG & ulCRC,INDEX iExtensiveSyncCheck) 
#line 121 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 122 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: ChecksumForSync  (ulCRC  , iExtensiveSyncCheck );
#line 123 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CRC_AddBlock  (ulCRC  , en_pcCharacter  . pc_aubGUID  , sizeof  (en_pcCharacter  . pc_aubGUID ));
#line 124 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CRC_AddBlock  (ulCRC  , en_pcCharacter  . pc_aubAppearance  , sizeof  (en_pcCharacter  . pc_aubAppearance ));
#line 125 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
  void CPlayerEntity::DumpSync_t(CTStream & strm,INDEX iExtensiveSyncCheck) 
#line 128 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{
#line 129 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
CMovableModelEntity  :: DumpSync_t  (strm  , iExtensiveSyncCheck );
#line 130 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("player: %s\n" , 
#line 131 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
(const char  *) en_pcCharacter  . GetName  ());
#line 132 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("GUID: ");
#line 133 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{for(INDEX i  = 0;i  < static_cast  < INDEX > (sizeof  (en_pcCharacter  . pc_aubGUID ));i  ++){
#line 134 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("%02X" , en_pcCharacter  . pc_aubGUID  [ i  ]);
#line 135 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}}
#line 136 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("\n");
#line 137 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("appearance: ");
#line 138 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
{for(INDEX i  = 0;i  < MAX_PLAYERAPPEARANCE ;i  ++){
#line 139 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("%02X" , en_pcCharacter  . pc_aubAppearance  [ i  ]);
#line 140 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}}
#line 141 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
strm  . FPrintF_t  ("\n");
#line 142 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
}
BOOL CPlayerEntity::
#line 145 "C:/VSProjects/SeriousSamClassic-DX9-MY/SamTFE/Sources.VS2015.BL.TFE.FONT.HUD-12.2025/Engine/Classes/PlayerEntity.es"
Dummy(const CEntityEvent &__eeInput) {
#undef STATE_CURRENT
#define STATE_CURRENT STATE_CPlayerEntity_Dummy
  ASSERTMSG(__eeInput.ee_slEvent==EVENTCODE_EVoid, "CPlayerEntity::Dummy expects 'EVoid' as input!");  const EVoid &e = (const EVoid &)__eeInput; ASSERT(FALSE); return TRUE;};